### ISSUE TITLE
Improve documentation: How to log / debug generated SQL in applications

### ISSUE THREAD

**Issue by ieugen** [graphqlize/honeyeql#4]
Hi,

Working with graphqlize-demo I did not found how to enable logging for the generated SQL.
It would be great if this was available in a documentation section. 

I'm thinking of something like the logging found in spring apps which I am familiar with: https://www.baeldung.com/spring-boot-testing-log-level

I should be able to do something like
````
logging.level.honeyeql=DEBUG 
````

And see the produced output. 

Thanks,
Eugen

**Comment by tamizhvendan** [comment]
As replied [in this comment](https://github.com/graphqlize/graphqlize/issues/51#issuecomment-613495760), this will be added in a future release.

**Comment by tamizhvendan** [comment]
Added [documentation](https://cljdoc.org/d/org.graphqlize/honeyeql/0.1.0-alpha44/doc/debugging-troubleshooting) on how to log & debug.
